#!/usr/bin/python3

import fileinput
import subprocess
import sys
import os
import re
import configparser

if "configure" not in sys.argv:
	sys.exit(0)


def log(text):
	print("\n>>> \033[32m" + text + "\033[0m\n")


def handleStatus(status):
	if status != 0:
		print("\033[31mError while running last command\033[0m")
		sys.exit(1)


sc = subprocess.call

if "upgrade" in sys.argv:
	if os.path.exists("/tmp/howdy_config_backup_v" + sys.argv[2] + ".ini"):
		oldConf = configparser.ConfigParser()
		oldConf.read("/tmp/howdy_config_backup_v" + sys.argv[2] + ".ini")
		newConf = configparser.ConfigParser()
		newConf.read("/etc/howdy/config.ini")

		for section in oldConf.sections():
			for (key, value) in oldConf.items(section):
				if key == "device_id":
					key = "device_path"
					value = "/dev/video" + value
				if key == "timout":
					key = "timeout"
				if key == "dismiss_lockscreen":
					if value == "true":
						print("DEPRECATION: Config value dismiss_lockscreen is no longer supported because of login loop issues.")
					continue
				if key == "capture_failed" or key == "capture_successful":
					if value == "true":
						print("NOTICE: Howdy login image captures have been disabled by default, change the config to enable them again")
						value = "false"
				if key == "ignore_ssh":
					key = "abort_if_ssh"
				if key == "ignore_closed_lid":
					key = "abort_if_lid_closed"
				if key == "capture_failed":
					key = "save_failed"
				if key == "capture_successful":
					key = "save_successful"
				try:
					newConf.set(section, key, value)
				except configparser.NoSectionError:
					newConf.add_section(section)
					newConf.set(section, key, value)

		with open("/etc/howdy/config.ini", "w") as configfile:
			newConf.write(configfile)

	sys.exit(0)

log("Configuring howdy")

handleStatus(sc(["chmod 755 -R /lib/security/howdy/"], shell=True))
handleStatus(sc(["chmod 755 -R /etc/howdy/"], shell=True))

os.chmod("/lib/security/howdy", 0o755)
os.chmod("/lib/security/howdy/cli.py", 0o755)
handleStatus(sc(["chmod 755 -R /lib/security/howdy/cli"], shell=True))
print("Permissions set")

os.symlink("/lib/security/howdy/cli.py", "/usr/local/bin/howdy")
os.chmod("/usr/local/bin/howdy", 0o755)
print("Howdy command installed")

log("Adding howdy as PAM module")

handleStatus(subprocess.call(["pam-auth-update --package"], shell=True))

print("Installation complete.")
